package com.mars.rti.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;




/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "collection", schema = "egovrti")
public class Collection 
{

	
	@Id	
	@Column(name="collection_id", nullable = false, unique = true)	
	@SequenceGenerator(name="collection_seq", sequenceName="collection_seq")
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="collection_seq") 
	private long collectionId; 
	
//	@OneToOne(cascade=CascadeType.ALL ,fetch = FetchType.LAZY, optional = false)
	@Column(name = "rti_application_id", nullable = false)
	private long rtiApplication ;//= new RTIApplication();
 
	@Column(name = "payment_mode")
	private String paymentMode;
	
	@Column(name = "receipt_number")
	private String receiptNumber;
	
	@Column(name = "receipt_date")
	private String receiptDate;	
	
	@Column(name = "cheque_dd_rtgs_number")
	private String chequeDDRTGSNumber;
	

	@Column(name = "status")
	private int status;
	
	@Column(name = "cheque_dd_rtgs_date")
	private String chequeDDRTGSDate;
	
	@Column(name = "bank_name")
	private String bankName;
	
	@Column(name = "branch_name")
	private String branchName; 
	
	@Column(name = "amount")
	private double amount;
	
	@Column(name = "amount_paid")
	private double amountPaid;
	
	
	@Column(name = "txn_num")
	private String UniqPgid;
	
	@Column(name = "reference_number")
	private String referenceNumber;
	
	@Column(name = "user_id")
	private String user_id;
	
	@Column(name = "user_name")
	private String user_name;
	
	@Column(name = "user_dept")
	private String user_dept;
	
	@Column(name = "user_machine_ip")
	private String user_machine_ip;
	
	@Column(name = "user_time")
	private String user_time;
	
	
	

	public String getUser_id() {
		return user_id;
	}

	public void setUser_id(String user_id) {
		this.user_id = user_id;
	}

	public String getUser_name() {
		return user_name;
	}

	public void setUser_name(String user_name) {
		this.user_name = user_name;
	}

	

	public String getUser_machine_ip() {
		return user_machine_ip;
	}

	public void setUser_machine_ip(String user_machine_ip) {
		this.user_machine_ip = user_machine_ip;
	}

	public String getUser_time() {
		return user_time;
	}

	public void setUser_time(String user_time) {
		this.user_time = user_time;
	}

	public String getReferenceNumber() {
		return referenceNumber;
	}

	public void setReferenceNumber(String referenceNumber) {
		this.referenceNumber = referenceNumber;
	}

	public String getUniqPgid() {
		return UniqPgid;
	}

	public void setUniqPgid(String uniqPgid) {
		UniqPgid = uniqPgid;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public long getCollectionId() {
		return collectionId;
	}

	public void setCollectionId(long collectionId) {
		this.collectionId = collectionId;
	}

	public long getRtiApplication() {
		return rtiApplication;
	}

	public void setRtiApplication(long rtiApplication) {
		this.rtiApplication = rtiApplication;
	}
		
	public String getPaymentMode() {
		return paymentMode;
	}

	public void setPaymentMode(String paymentMode) {
		this.paymentMode = paymentMode;
	}

	public String getReceiptNumber() {
		return receiptNumber;
	}

	public void setReceiptNumber(String receiptNumber) {
		this.receiptNumber = receiptNumber;
	}
		
	public String getReceiptDate() {
		return receiptDate;
	}

	public void setReceiptDate(String receiptDate) {
		this.receiptDate = receiptDate;
	}

	public String getChequeDDRTGSNumber() {
		return chequeDDRTGSNumber;
	}

	public void setChequeDDRTGSNumber(String chequeDDRTGSNumber) {
		this.chequeDDRTGSNumber = chequeDDRTGSNumber;
	}

	public String getChequeDDRTGSDate() {
		return chequeDDRTGSDate;
	}

	public void setChequeDDRTGSDate(String chequeDDRTGSDate) {
		this.chequeDDRTGSDate = chequeDDRTGSDate;
	}

	public String getBankName() {
		return bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public String getBranchName() {
		return branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	public double getAmount() {
		return amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	public double getAmountPaid() {
		return amountPaid;
	}

	public void setAmountPaid(double amountPaid) {
		this.amountPaid = amountPaid;
	}

	public String getUser_dept() {
		return user_dept;
	}

	public void setUser_dept(String user_dept) {
		this.user_dept = user_dept;
	}

	 
	    
}
