package com.mars.rti.model;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.mars.common.model.DeliveryMode;




/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "draft_sent_through", schema = "egovrti")
public class DraftSentThrough 
{

	
	@Id	
	@Column(name="draft_sent_through_id", nullable = false, unique = true)	
	@SequenceGenerator(name="draft_sent_through_seq", sequenceName="draft_sent_through_seq")
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="draft_sent_through_seq") 
	private long draftSentThroughId;
		    
	@ManyToOne
	@JoinColumn(name = "draft_id" )
	private Draft  draft ; 
	
	@ManyToOne
	@JoinColumn(name = "delivery_mode_id")
	private DeliveryMode deliveryMode ;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "draftSentThrough", cascade = CascadeType.ALL)
	private List<DraftSentThroughDetails> draftSentThroughDetailsList = new ArrayList<DraftSentThroughDetails>();

	public long getDraftSentThroughId() {
		return draftSentThroughId;
	}

	public void setDraftSentThroughId(long draftSentThroughId) {
		this.draftSentThroughId = draftSentThroughId;
	}

	public Draft getDraft() {
		return draft;
	}

	public void setDraft(Draft draft) {
		this.draft = draft;
	}


	public DeliveryMode getDeliveryMode() {
		return deliveryMode;
	}

	public void setDeliveryMode(DeliveryMode deliveryMode) {
		this.deliveryMode = deliveryMode;
	}

	public List<DraftSentThroughDetails> getDraftSentThroughDetailsList() {
		return draftSentThroughDetailsList;
	}

	public void setDraftSentThroughDetailsList(
			List<DraftSentThroughDetails> draftSentThroughDetailsList) {
		this.draftSentThroughDetailsList = draftSentThroughDetailsList;
	}

 
	 
	
	
    
}
