package com.mars.rti.model;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.mars.common.model.Tenancy;
import com.mars.common.model.User;




/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "draft", schema = "egovrti")
public class Draft 
{

	
	@Id	
	@Column(name="draft_id", nullable = false, unique = true)	
	@SequenceGenerator(name="draft_seq", sequenceName="draft_seq")
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="draft_seq") 
	private long draftId;
		
 
	@Column(name = "draft_number", nullable = false)
    private String draftNumber;
	 	
	@Column(name = "sent_status", nullable = true)
    private Integer sentStatus;
	
	@Column(name = "creation_date", nullable = false)
    private String creationDate ;
	
	@Column(name = "sent_date" )
	private String sentDate ; 

 	@Column(name = "draft_content", nullable = false)
    private String draftContent;  	
 	
 	@ManyToOne
	@JoinColumn(name = "rti_application_id", nullable = false)
	private RTIApplication rtiApplication = new RTIApplication();
		
 	@ManyToOne
	@JoinColumn(name = "sent_by_user" , nullable = true)
	private User sentByUser = null;
 	
 	@ManyToOne
	@JoinColumn(name = "created_by_user" , nullable = true)
	private User createdByUser = null;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "draft", cascade = CascadeType.ALL)
	private List<DraftSentThrough> draftsSentThroughList = new ArrayList<DraftSentThrough>();

	@ManyToOne
	@JoinColumn(name = "tenancyid", nullable = true)
    private Tenancy tenancy=null ;
	
	@ManyToOne
	@JoinColumn(name = "draft_type_id", nullable = true)
    private DraftType draftType=null ;
	

	public long getDraftId() {
		return draftId;
	}

	public void setDraftId(long draftId) {
		this.draftId = draftId;
	}
 

	public String getDraftNumber() {
		return draftNumber;
	}

	public void setDraftNumber(String draftNumber) {
		this.draftNumber = draftNumber;
	}

	public Integer getSentStatus() {
		return sentStatus;
	}

	public void setSentStatus(Integer sentStatus) {
		this.sentStatus = sentStatus;
	}

	public String getCreationDate() {
		return creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	public String getSentDate() {
		return sentDate;
	}

	public void setSentDate(String sentDate) {
		this.sentDate = sentDate;
	}

	public String getDraftContent() {
		return draftContent;
	}

	public void setDraftContent(String draftContent) {
		this.draftContent = draftContent;
	}

	public User getSentByUser() {
		return sentByUser;
	}

	public void setSentByUser(User sentByUser) {
		this.sentByUser = sentByUser;
	}

	public User getCreatedByUser() {
		return createdByUser;
	}

	public void setCreatedByUser(User createdByUser) {
		this.createdByUser = createdByUser;
	}

	public RTIApplication getRtiApplication() {
		return rtiApplication;
	}

	public void setRtiApplication(RTIApplication rtiApplication) {
		this.rtiApplication = rtiApplication;
	}
	
 	public List<DraftSentThrough> getDraftsSentThroughList() {
		return draftsSentThroughList;
	}

	public void setDraftsSentThroughList(
			List<DraftSentThrough> draftsSentThroughList) {
		this.draftsSentThroughList = draftsSentThroughList;
	}

	public Tenancy getTenancy() {
		return tenancy;
	}

	public void setTenancy(Tenancy tenancy) {
		this.tenancy = tenancy;
	}

	public DraftType getDraftType() {
		return draftType;
	}

	public void setDraftType(DraftType draftType) {
		this.draftType = draftType;
	} 
	     
}
