package com.mars.rti.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.mars.common.model.User;




/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "rti_application_reassign_acceptance", schema = "egovrti")
public class RTIApplicationReAssignAcceptance 
{

	
	@Id	
	@Column(name="rti_application_reassign_acceptance_id", nullable = false, unique = true)	
	@SequenceGenerator(name="rti_application_reassign_acceptance_seq", sequenceName="rti_application_reassign_acceptance_seq")
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="rti_application_reassign_acceptance_seq") 
	private long RTIApplicationReAssignAcceptanceId;
			 	
 	@ManyToOne
	@JoinColumn(name = "rti_application_id", nullable = false)
	private RTIApplication rtiApplication = new RTIApplication();
		
 	@ManyToOne
	@JoinColumn(name = "assigned_by" , nullable = true)
	private User assignedBy = null;
 	
 	@ManyToOne
	@JoinColumn(name = "assigned_to" , nullable = true)
	private User assignedTo = null;
	
 	//0- assigned, 1 = accept , 2 reject to accept
 	@Column(name = "accept_status" , nullable = true)
    private Integer acceptStatus;
    
 	@Column(name = "assigned_date" , nullable = true)
    private String assignedDate;
 	
 	@Column(name = "accept_or_reject_date" , nullable = true)
    private String acceptOrRejectDate;
 	
 	
 	@Column(name = "accept_or_reject_remarks" , nullable = true)
    private String acceptOrRejectRemarks;

	public long getRTIApplicationReAssignAcceptanceId() {
		return RTIApplicationReAssignAcceptanceId;
	}

	public void setRTIApplicationReAssignAcceptanceId(
			long rTIApplicationReAssignAcceptanceId) {
		RTIApplicationReAssignAcceptanceId = rTIApplicationReAssignAcceptanceId;
	}

	public RTIApplication getRtiApplication() {
		return rtiApplication;
	}

	public void setRtiApplication(RTIApplication rtiApplication) {
		this.rtiApplication = rtiApplication;
	}

	public User getAssignedBy() {
		return assignedBy;
	}

	public void setAssignedBy(User assignedBy) {
		this.assignedBy = assignedBy;
	}

	public User getAssignedTo() {
		return assignedTo;
	}

	public void setAssignedTo(User assignedTo) {
		this.assignedTo = assignedTo;
	}

	public Integer getAcceptStatus() {
		return acceptStatus;
	}

	public void setAcceptStatus(Integer acceptStatus) {
		this.acceptStatus = acceptStatus;
	}

	public String getAssignedDate() {
		return assignedDate;
	}

	public void setAssignedDate(String assignedDate) {
		this.assignedDate = assignedDate;
	}

	public String getAcceptOrRejectDate() {
		return acceptOrRejectDate;
	}

	public void setAcceptOrRejectDate(String acceptOrRejectDate) {
		this.acceptOrRejectDate = acceptOrRejectDate;
	}

	public String getAcceptOrRejectRemarks() {
		return acceptOrRejectRemarks;
	}

	public void setAcceptOrRejectRemarks(String acceptOrRejectRemarks) {
		this.acceptOrRejectRemarks = acceptOrRejectRemarks;
	}
	
	
}
