package com.mars.rti.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;




/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "rti_application_actions", schema = "egovrti")
public class RTIApplicationActions implements java.io.Serializable
{
	
	@Id	
	@Column(name="rti_application_actions_id", nullable = false, unique = true)	
	@SequenceGenerator(name="rti_application_actions_seq", sequenceName="rti_application_actions_seq")
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="rti_application_actions_seq") 
	private long rtiApplicationActionsId;
		
	@ManyToOne
	@JoinColumn(name = "rti_application_id", nullable = false)
	private RTIApplication rtiApplication= new RTIApplication();
	
	@ManyToOne
	@JoinColumn(name = "rti_application_details_id", nullable = false)
	private RTIApplicationDetails rtiApplicationDetails= new RTIApplicationDetails();
		
	@Column(name = "status", nullable = true)
    private Integer status;

	@Column(name = "tenancyid", nullable = true)
	private int tenancyId;

	
	public long getRtiApplicationActionsId() {
		return rtiApplicationActionsId;
	}

	public void setRtiApplicationActionsId(long rtiApplicationActionsId) {
		this.rtiApplicationActionsId = rtiApplicationActionsId;
	}

	public RTIApplication getRtiApplication() {
		return rtiApplication;
	}

	public void setRtiApplication(RTIApplication rtiApplication) {
		this.rtiApplication = rtiApplication;
	}

	public RTIApplicationDetails getRtiApplicationDetails() {
		return rtiApplicationDetails;
	}

	public void setRtiApplicationDetails(RTIApplicationDetails rtiApplicationDetails) {
		this.rtiApplicationDetails = rtiApplicationDetails;
	}

	public int getTenancyId() {
		return tenancyId;
	}

	public void setTenancyId(int tenancyId) {
		this.tenancyId = tenancyId;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}
	
}