package com.mars.rti.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.mars.common.model.Department;
import com.mars.common.model.Section;
import com.mars.common.model.User;
import com.mars.common.utils.CommonUtils;




/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "rti_application_details", schema = "egovrti")
public class RTIApplicationDetails 
{

	
	@Id	
	@Column(name="rti_application_details_id", nullable = false, unique = true)	
	@SequenceGenerator(name="rti_application_details_seq", sequenceName="rti_application_details_seq")
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="rti_application_details_seq") 
	private long rtiApplicationDetailsId;
		
	    
	@ManyToOne
	@JoinColumn(name = "rti_application_id", nullable = false)
	private RTIApplication rtiApplication ;//= new RTIApplication();
	
	
	@Column(name = "status", nullable = true)
    private Integer status;
	
	@Column(name = "created_date", nullable = false)
    private String createdDate=CommonUtils.getCurrentStringUIDate();
	
	@Column(name = "comments", nullable = true)
    private String comments;
	
	
	@ManyToOne
    @JoinColumn(name = "department_id")
	private Department department = null;//new Department();
	
	@ManyToOne
    @JoinColumn(name = "section_id")
	private Section section = null;//new Section();
	
	@ManyToOne
	@JoinColumn(name = "user_id" , nullable = true)
	private User user = null;
	
	@ManyToOne
	@JoinColumn(name = "to_user_id" , nullable = true)
	private User toUser = null;
	
	@Column(name = "assign_to_status", nullable = true)
    private Integer assignToStatus;
	
	@Column(name = "assigned_start_date", nullable = true)
    private String assignedStartDate;
	
	@Column(name = "assigned_end_date", nullable = true)
    private String assignedEndDate;
	
	@Column(name = "workflow_level", nullable = true)
    private Integer workflowLevel;

	 

	public long getRtiApplicationDetailsId() {
		return rtiApplicationDetailsId;
	}

	public void setRtiApplicationDetailsId(long rtiApplicationDetailsId) {
		this.rtiApplicationDetailsId = rtiApplicationDetailsId;
	}

	public RTIApplication getRtiApplication() {
		return rtiApplication;
	}

	public void setRtiApplication(RTIApplication rtiApplication) {
		this.rtiApplication = rtiApplication;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(String createdDate) {
		this.createdDate = createdDate;
	}

	public String getComments() {
		return comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Department getDepartment() {
		return department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public Section getSection() {
		return section;
	}

	public void setSection(Section section) {
		this.section = section;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public User getToUser() {
		return toUser;
	}

	public void setToUser(User toUser) {
		this.toUser = toUser;
	}

	public Integer getAssignToStatus() {
		return assignToStatus;
	}

	public void setAssignToStatus(Integer assignToStatus) {
		this.assignToStatus = assignToStatus;
	}

	public String getAssignedStartDate() {
		return assignedStartDate;
	}

	public void setAssignedStartDate(String assignedStartDate) {
		this.assignedStartDate = assignedStartDate;
	}

	public String getAssignedEndDate() {
		return assignedEndDate;
	}

	public void setAssignedEndDate(String assignedEndDate) {
		this.assignedEndDate = assignedEndDate;
	}

	public Integer getWorkflowLevel() {
		return workflowLevel;
	}

	public void setWorkflowLevel(Integer workflowLevel) {
		this.workflowLevel = workflowLevel;
	}

	 
	    
}
