package com.mars.rti.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.mars.common.model.User;
import com.mars.common.utils.CommonUtils;




/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "rti_application_notings", schema = "egovrti")
public class RTIApplicationNoting 
{
	
	@Id	
	@Column(name="rti_application_noting_id", nullable = false, unique = true)	
	@SequenceGenerator(name="rti_application_noting_seq", sequenceName="rti_application_noting_seq")
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="rti_application_noting_seq") 
	private long rtiApplicationNotingId;
			    
	@ManyToOne
	@JoinColumn(name = "rti_application_id", nullable = false)
	private RTIApplication rtiApplication ;//= new RTIApplication();
	 
	
	@Column(name = "rti_application_details_id", nullable = true)
    private long rtiApplicationDetailsId;
	
	@Column(name = "status", nullable = true)
    private Integer status;
	
	@Column(name = "noting_date", nullable = false)
    private String notingDate=CommonUtils.getCurrentStringDateAndTime();
			
	@Column(name = "noting", nullable = true)
    private String noting;
	
	@ManyToOne
	@JoinColumn(name = "noting_user_id" , nullable = true)
	private User notingUser = null;
	 	
	public long getRtiApplicationNotingId() {
		return rtiApplicationNotingId;
	}

	public void setRtiApplicationNotingId(long rtiApplicationNotingId) {
		this.rtiApplicationNotingId = rtiApplicationNotingId;
	}

	public RTIApplication getRtiApplication() {
		return rtiApplication;
	}

	public void setRtiApplication(RTIApplication rtiApplication) {
		this.rtiApplication = rtiApplication;
	}

	 

	public long getRtiApplicationDetailsId() {
		return rtiApplicationDetailsId;
	}

	public void setRtiApplicationDetailsId(long rtiApplicationDetailsId) {
		this.rtiApplicationDetailsId = rtiApplicationDetailsId;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getNotingDate() {
		return notingDate;
	}

	public void setNotingDate(String notingDate) {
		this.notingDate = notingDate;
	}

	public String getNoting() {
		return noting;
	}

	public void setNoting(String noting) {
		this.noting = noting;
	}

	public User getNotingUser() {
		return notingUser;
	}

	public void setNotingUser(User notingUser) {
		this.notingUser = notingUser;
	}
	
	
		   
}
