package com.mars.rti.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.mars.common.model.User;
import com.mars.common.utils.CommonUtils;




/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "rti_application_park", schema = "egovrti")
public class RTIApplicationPark 
{
	
	@Id	
	@Column(name="rti_application_park_id", nullable = false, unique = true)	
	@SequenceGenerator(name="rti_application_park_seq", sequenceName="rti_application_park_seq")
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="rti_application_park_seq") 
	private long rtiApplicationParkId;
			    
	@ManyToOne
	@JoinColumn(name = "rti_application_id", nullable = false)
	private RTIApplication rtiApplication= new RTIApplication();
	
	@Column(name = "status", nullable = true)
    private Integer status;	
			
	@Column(name = "parked_remarks", nullable = true)
    private String parkedRemarks;
	
	@Column(name = "un_parked_remarks", nullable = true)
    private String unParkedRemarks;
	
	@ManyToOne
	@JoinColumn(name = "parked_by" , nullable = true)
	private User parkedBy = null;
	
	@ManyToOne
	@JoinColumn(name = "un_parked_by" , nullable = true)
	private User unParkedBy = null;
		
	@Column(name = "parked_date" )
    private String parkedDate = CommonUtils.getCurrentStringDateAndTime();
	
	@Column(name = "un_parked_date")
    private String unParkedDate = null;
	
	@Column(name = "reminder_date", nullable = false)
    private String reminderDate = null;

	
	
	public String getReminderDate() {
		return reminderDate;
	}

	public void setReminderDate(String reminderDate) {
		this.reminderDate = reminderDate;
	}

	 

	public long getRtiApplicationParkId() {
		return rtiApplicationParkId;
	}

	public void setRtiApplicationParkId(long rtiApplicationParkId) {
		this.rtiApplicationParkId = rtiApplicationParkId;
	}

	public RTIApplication getRtiApplication() {
		return rtiApplication;
	}

	public void setRtiApplication(RTIApplication rtiApplication) {
		this.rtiApplication = rtiApplication;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getParkedRemarks() {
		return parkedRemarks;
	}

	public void setParkedRemarks(String parkedRemarks) {
		this.parkedRemarks = parkedRemarks;
	}

	public String getUnParkedRemarks() {
		return unParkedRemarks;
	}

	public void setUnParkedRemarks(String unParkedRemarks) {
		this.unParkedRemarks = unParkedRemarks;
	}

	public User getParkedBy() {
		return parkedBy;
	}

	public void setParkedBy(User parkedBy) {
		this.parkedBy = parkedBy;
	}

	public User getUnParkedBy() {
		return unParkedBy;
	}

	public void setUnParkedBy(User unParkedBy) {
		this.unParkedBy = unParkedBy;
	}

	public String getParkedDate() {
		return parkedDate;
	}

	public void setParkedDate(String parkedDate) {
		this.parkedDate = parkedDate;
	}

	public String getUnParkedDate() {
		return unParkedDate;
	}

	public void setUnParkedDate(String unParkedDate) {
		this.unParkedDate = unParkedDate;
	}


	
	
		   
}
