package com.mars.rti.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.mars.common.utils.CommonUtils;




/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "rti_application_details", schema = "egovrti")
public class RTIApplicationDetailsBAckup implements java.io.Serializable
{

	
	@Id	
	@Column(name="rti_application_details_id", nullable = false, unique = true)	
	@SequenceGenerator(name="rti_application_details_seq", sequenceName="rti_application_details_seq")
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="rti_application_details_seq") 
	private long rtiApplicationDetailsId;
		    
	@ManyToOne
	@JoinColumn(name = "rti_application_id", nullable = false)
	private RTIApplication rtiApplication= new RTIApplication();
		
	@Column(name = "user_id", nullable=false)	
	private long userId;	
	
	@Column(name = "status", nullable = true)
    private Integer status;
	
	@Column(name = "created_date", nullable = false)
    private String createdDate=CommonUtils.getCurrentStringUIDate();
	
	@Column(name = "comments", nullable = true)
    private String comments;

	public String getComments() {
		return comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}
	 

	public String getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(String createdDate) {
		this.createdDate = createdDate;
	}

	public long getRtiApplicationDetailsId() {
		return rtiApplicationDetailsId;
	}

	public void setRtiApplicationDetailsId(long rtiApplicationDetailsId) {
		this.rtiApplicationDetailsId = rtiApplicationDetailsId;
	}

	public long getUserId() {
		return userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public RTIApplication getRtiApplication() {
		return rtiApplication;
	}

	public void setRtiApplication(RTIApplication rtiApplication) {
		this.rtiApplication = rtiApplication;
	}
	
}
