#SSO client and server url
cas.sso.client.url=http://172.16.25.46:9046/RTI
cas.sso.server.url=http://172.16.25.46:9046/cas-server


# GIS Server Details
gis.server.url=http://119.226.93.115:9090
#gis.server.url=http://172.16.25.60:9090


#DMS repository url
jackrabbit.repository.dms.url=rmi://172.16.25.211:8888
jackrabbit.repository.dms.workspacename=FTS
jackrabbit.repository.dms.username=admin
jackrabbit.repository.dms.password=password	

# Rest Service Settings
rest.service.username=admin
rest.service.password=password

# FAS Server Settings
fas.server.url=http://172.16.25.41:9091/fas
fas.server.username=Admin
fas.server.password=password

# MAIL CONFIGURATIONS
mail.smtp.from=Jaipur Municipal Corporation
mail.smtp.host=smtp.gmail.com
mail.smtp.port=465
mail.smtp.auth=true
mail.smtp.startssl.enable=false
mail.smtp.starttls.enable=true
mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
mail.transport.protocol=smtps
mail.debug=false
mail.smtp.quitwait=true
mail.username=info.smartrajportal@gmail.com
mail.password=portal1234
mail.subject=SMARTRAJ RTI MAIL
mail.sender=SMARTRAJ
mail.send.afterspecificperiod=15


#mail.smtp.from=Jaipur Municipal Corporation
#mail.smtp.host=smtp.gmail.com
#mail.smtp.port=465
#mail.smtp.auth=true
#mail.smtp.startssl.enable=false
#mail.smtp.starttls.enable=true
#mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
#mail.transport.protocol=smtps
#mail.debug=false
#mail.smtp.quitwait=true
#mail.username=info.smartrajportal@gmail.com
#mail.password=portal1234
#mail.subject=SMARTRAJ RTI MAIL
#mail.sender=SMARTRAJ
#mail.send.afterspecificperiod=15


# Quartz properties
mars.quartz.scheduler.instanceName=DefaultQuartzScheduler
mars.quartz.scheduler.rmi.export=false
mars.quartz.scheduler.rmi.proxy=false
mars.quartz.scheduler.wrapJobExecutionInUserTransaction=false
mars.quartz.scheduler.skipUpdateCheck=true

mars.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX
mars.quartz.jobStore.tablePrefix=QRTZ_
mars.quartz.jobStore.maxMisfiresToHandleAtATime=20
mars.quartz.jobStore.txIsolationLevelSerializable=false
mars.quartz.jobStore.useProperties=false
mars.quartz.jobStore.dontSetAutoCommitFalse=false
mars.quartz.jobStore.clusterCheckinInterval=15000
mars.quartz.jobStore.misfireThreshold=60000
mars.quartz.jobStore.isClustered=false
mars.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
#quartz.delegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
mars.quartz.jobStore.selectWithLockSQL=SELECT * FROM QRTZ_LOCKS WHERE LOCK_NAME = ? FOR UPDATE

mars.quartz.threadPool.class=org.quartz.simpl.SimpleThreadPool
mars.quartz.threadPool.threadCount=10
mars.quartz.threadPool.threadPriority=5
mars.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread=true


