package com.mars.rti.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;




/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "draft_type", schema = "egovrti")
public class DraftType 
{

	
	@Id	
	@Column(name="draft_type_id", nullable = false, unique = true)	
	@SequenceGenerator(name="draft_type_seq", sequenceName="draft_type_seq")
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="draft_type_seq") 
	private long draftTypeId;
		
	@Column(name = "draft_type_Name" )
    private String draftTypeName;
	
	@Column(name = "status" )
    private Integer status;

	public long getDraftTypeId() {
		return draftTypeId;
	}

	public void setDraftTypeId(long draftTypeId) {
		this.draftTypeId = draftTypeId;
	}

	public String getDraftTypeName() {
		return draftTypeName;
	}

	public void setDraftTypeName(String draftTypeName) {
		this.draftTypeName = draftTypeName;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}
	
 	 
    
}
